# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: oak9 Analysis Task@1
  inputs:
    serviceEndpoint: 'oak9ProdAakashPersonal'
    projectName: 'proj-aakashpersonal-9'
    qualityGate: 'Critical'
    pollingTimeoutSec: '300'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
